source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'pg'
gem 'puma', '~> 2.11.2'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'foreman'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'web-console', '~> 2.0'
end

group :test do
  gem 'rspec', '~> 3.2.0'
end
